# Generated by Django 4.2.9 on 2024-03-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_footage', models.PositiveIntegerField()),
                ('photos', models.ImageField(upload_to='property_photos/')),
                ('floor_plans', models.FileField(upload_to='floor_plans/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.FloatField()),
                ('loan_term', models.PositiveIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='HomeValueEstimator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configapp.property')),
            ],
        ),
    ]
